<template><div><p>Stream API是Java 8引入的一种新的集合操作方式，是一种链式API，可以极大简化集合操作。 Stream API的详细教程参见<a href="https://juejin.cn/post/6844903830254010381" target="_blank" rel="noopener noreferrer">掘金文档<ExternalLinkIcon/></a>。</p>
<!-- more -->
<h2 id="_1-问题span" tabindex="-1"><a class="header-anchor" href="#_1-问题span" aria-hidden="true">#</a> 1. 问题span</h2>
<hr>
<p>本人在公司写代码时，看到同事写的如下代码（内容已脱敏）。</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">boolean</span> <span class="token function">checkPhoneNumber</span><span class="token punctuation">(</span><span class="token class-name">String</span> phoneNumber<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>phoneNumber <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">PhoneNumberException</span><span class="token punctuation">(</span><span class="token string">"ERR001"</span><span class="token punctuation">,</span> <span class="token string">"电话号码为空！"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"134"</span><span class="token punctuation">)</span> 
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"135"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"136"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"137"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"138"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"139"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"147"</span><span class="token punctuation">)</span>
        <span class="token operator">||</span> phoneNumber<span class="token punctuation">.</span><span class="token function">startsWith</span><span class="token punctuation">(</span><span class="token string">"148"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>上述代码完成的事情非常简单，就是检查电话号码是不是以134（不含1349）、135、136、137、138、139、147或148开头。但是我们却足足要使用8个startWith方法，并将它们使用 <code v-pre>||</code>符号连接。这样的代码看起来十分简单粗暴，且极其占用篇幅，修改起来也是怕多一个空格少一个空格之类的。</p>
<h2 id="_2-使用正则表达式-通配电话号码" tabindex="-1"><a class="header-anchor" href="#_2-使用正则表达式-通配电话号码" aria-hidden="true">#</a> 2. 使用正则表达式，通配电话号码</h2>
<p>使用正则表达式是一种可取的方法。</p>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">boolean</span> <span class="token function">checkPhoneNumber</span><span class="token punctuation">(</span><span class="token class-name">String</span> phoneNumber<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>phoneNumber <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">PhoneNumberException</span><span class="token punctuation">(</span><span class="token string">"ERR001"</span><span class="token punctuation">,</span> <span class="token string">"电话号码为空！"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token class-name">String</span> regexp <span class="token operator">=</span> <span class="token string">"^(134)|(135)|(136)|(137)|(138)|(139)|(147)|(148).*$"</span><span class="token punctuation">;</span>
    <span class="token keyword">return</span> phoneNumber<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>regexp<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但是使用正则表达式，就意味着代码风险不可控。且正则表达式的程序不够通俗易懂。</p>
<h2 id="_3-使用stream-api" tabindex="-1"><a class="header-anchor" href="#_3-使用stream-api" aria-hidden="true">#</a> 3. 使用Stream API</h2>
<div class="language-java ext-java line-numbers-mode"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">boolean</span> <span class="token function">checkPhoneNumber</span><span class="token punctuation">(</span><span class="token class-name">String</span> phoneNumber<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>phoneNumber <span class="token operator">==</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token keyword">throw</span> <span class="token keyword">new</span> <span class="token class-name">PhoneNumberException</span><span class="token punctuation">(</span><span class="token string">"ERR001"</span><span class="token punctuation">,</span> <span class="token string">"电话号码为空！"</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> <span class="token class-name">Stream</span><span class="token punctuation">.</span><span class="token function">of</span><span class="token punctuation">(</span><span class="token string">"134"</span><span class="token punctuation">,</span><span class="token string">"135"</span><span class="token punctuation">,</span><span class="token string">"136"</span><span class="token punctuation">,</span><span class="token string">"137"</span><span class="token punctuation">,</span><span class="token string">"138"</span><span class="token punctuation">,</span><span class="token string">"139"</span><span class="token punctuation">,</span><span class="token string">"147"</span><span class="token punctuation">,</span><span class="token string">"148"</span><span class="token punctuation">)</span>
            <span class="token punctuation">.</span><span class="token function">anyMatch</span><span class="token punctuation">(</span>phoneNumber<span class="token operator">::</span><span class="token function">startsWith</span><span class="token punctuation">)</span><span class="token punctuation">;</span>  <span class="token comment">// 方法引用</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>这样，我们在保证了代码可读性与风险可控的前提下，又减小了程序的篇幅。</p>
</div></template>


