<template><div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code><span class="token keyword">from</span> redis <span class="token keyword">import</span> ConnectionPool<span class="token punctuation">,</span> Redis

pool <span class="token operator">=</span> ConnectionPool<span class="token punctuation">(</span>host<span class="token operator">=</span><span class="token string">'192.168.65.200'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">16379</span><span class="token punctuation">,</span> decode_responses<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span>
r <span class="token operator">=</span> Redis<span class="token punctuation">(</span>connection_pool<span class="token operator">=</span>pool<span class="token punctuation">)</span>

<span class="token keyword">for</span> m <span class="token keyword">in</span> r<span class="token punctuation">.</span>lpop<span class="token punctuation">(</span><span class="token string">"mylist"</span><span class="token punctuation">,</span> <span class="token number">3</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>m<span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-python ext-py line-numbers-mode"><pre v-pre class="language-python"><code>pool <span class="token operator">=</span> ConnectionPool<span class="token punctuation">(</span>host<span class="token operator">=</span><span class="token string">'192.168.65.200'</span><span class="token punctuation">,</span> port<span class="token operator">=</span><span class="token number">16379</span><span class="token punctuation">,</span> decode_responses<span class="token operator">=</span><span class="token boolean">True</span><span class="token punctuation">)</span>
r <span class="token operator">=</span> Redis<span class="token punctuation">(</span>connection_pool<span class="token operator">=</span>pool<span class="token punctuation">)</span>
p <span class="token operator">=</span> r<span class="token punctuation">.</span>pubsub<span class="token punctuation">(</span><span class="token punctuation">)</span>
p<span class="token punctuation">.</span>psubscribe<span class="token punctuation">(</span><span class="token string">"A:*"</span><span class="token punctuation">)</span>
<span class="token keyword">for</span> item <span class="token keyword">in</span> p<span class="token punctuation">.</span>listen<span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    <span class="token keyword">print</span><span class="token punctuation">(</span>item<span class="token punctuation">)</span>

<span class="token keyword">for</span> i <span class="token keyword">in</span> <span class="token builtin">range</span><span class="token punctuation">(</span><span class="token number">10</span><span class="token punctuation">)</span><span class="token punctuation">:</span>
    r<span class="token punctuation">.</span>publish<span class="token punctuation">(</span><span class="token string">"A:B"</span><span class="token punctuation">,</span> <span class="token string">"hello"</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


